import streamlit as st
import asyncio
import time
from orchestrator import AgentNode, WorkflowDAG
from agent_tasks import syllabus_generator_agent, chapter_writer_agent

# Set up clean web page configurations
st.set_page_config(page_title="AI Multi-Agent Course Factory", page_icon="🎓", layout="wide")

st.title("🎓 AI Multi-Agent Course Generation Factory")
st.caption("Powered by a custom Asynchronous Directed Acyclic Graph (DAG) Engine & Gemini")

# Initialize session state tracking variables so Streamlit remembers data across clicks
if "syllabus_ready" not in st.session_state:
    st.session_state.syllabus_ready = False
if "initial_context" not in st.session_state:
    st.session_state.initial_context = {}
if "chapters" not in st.session_state:
    st.session_state.chapters = []

# --- 1. USER INPUT INPUT SECTION ---
st.subheader("🎯 Step 1: Define Your Target Course Topic")
user_topic = st.text_input("Enter the technical topic you want to generate a deep-dive course for:", 
                            placeholder="e.g., Lock-Free Data Structures in C++")

# Helper function to execute the async syllabus generator safely inside Streamlit
def run_async_syllabus(topic_string):
    initial_ctx = {"topic": topic_string}
    # Run the async agent block natively inside a clean execution loop
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    result_state = loop.run_until_complete(syllabus_generator_agent(initial_ctx))
    loop.close()
    return result_state

if st.button("🚀 Generate Course Outline"):
    if not user_topic.strip():
        st.error("Please enter a valid topic first!")
    else:
        with st.spinner("🤖 [Syllabus Agent] Querying Gemini and verifying structural JSON schema..."):
            try:
                # Run backend syllabus engine
                interim_state = run_async_syllabus(user_topic)
                
                # Save results to session state memory
                st.session_state.initial_context = {"topic": user_topic}
                st.session_state.initial_context.update(interim_state)
                st.session_state.chapters = interim_state.get("chapters_to_write", [])
                st.session_state.syllabus_ready = True
                st.rerun()
            except Exception as e:
                st.error(f"Failed to generate syllabus: {e}")

# --- 2. HUMAN-IN-THE-LOOP (HITL) GATEWAY SECTION ---
if st.session_state.syllabus_ready:
    st.markdown("---")
    st.subheader("🛑 Step 2: Human-in-the-Loop Validation Gate")
    
    col1, col2 = st.columns([1, 2])
    with col1:
        st.metric(label="Total Proposed Chapters", value=len(st.session_state.chapters))
        st.info("Review the schema-aligned structure generated by the agent matrix on the right before triggering parallel generation.")
        
    with col2:
        st.markdown(f"**Course Title:** {st.session_state.initial_context['course_metadata']['topic']}")
        st.markdown(f"**Target Audience Experience:** `{st.session_state.initial_context['course_metadata']['audience']}`")
        
        # Display the interactive checklist
        st.write("### 📋 Generated Course Modules Blueprint:")
        for idx, ch in enumerate(st.session_state.chapters):
            st.markdown(f"**{idx+1}. {ch.get('title')}**")
            st.caption(ch.get('summary'))

    st.markdown("---")
    
    # Helper function to run the full async parallel graph execution
    def run_parallel_generation(context, chapters_list):
        dag = WorkflowDAG()
        dag.add_node(AgentNode("Syllabus_Gen", syllabus_generator_agent))
        
        # Dynamically map out parallel dependency paths based on verified user components
        for idx, ch in enumerate(chapters_list):
            node_id = f"Writer_Chapter_{idx+1}"
            async def make_writer_task(state, ch_data=ch):
                state_copy = dict(state)
                state_copy["current_processing_node"] = ch_data
                return await chapter_writer_agent(state_copy)
            dag.add_node(AgentNode(node_id, make_writer_task))
            dag.add_dependency("Syllabus_Gen", node_id)
            
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        final_state = loop.run_until_complete(dag.run(context))
        loop.close()
        return final_state

    # Action buttons for the user validation layer

st.markdown("### 💬 Want to modify the outline before drafting?")
user_feedback = st.text_area(
    "Suggest changes (optional):",
    placeholder="e.g., Remove chapter 3, add a chapter on heap sort, make it more beginner friendly..."
)

c1, c2, c3 = st.columns([2, 2, 5])

with c1:
    if st.button("✅ Approve & Draft Content", type="primary"):
        with st.spinner("⚡ Spawning parallel branch nodes..."):
            start_time = time.time()
            final_output = run_parallel_generation(
                st.session_state.initial_context, 
                st.session_state.chapters
            )
            end_time = time.time()
            st.success(f"🎉 Pipeline completed in {end_time - start_time:.2f} seconds!")
            st.subheader("📚 Generated Textbook Drafts")
            for key, val in final_output.items():
                if key.startswith("content_"):
                    with st.expander(f"📖 {key.replace('content_', '').replace('_', ' ')}"):
                        st.markdown(val)

with c2:
    if st.button("🔄 Suggest Changes"):
        if not user_feedback.strip():
            st.warning("Please type your suggestions in the box above first!")
        else:
            with st.spinner("🤖 Re-generating syllabus with your feedback..."):
                try:
                    revised_topic = f"{st.session_state.initial_context['topic']}. User feedback: {user_feedback}"
                    revised_state = run_async_syllabus(revised_topic)
                    st.session_state.initial_context = {"topic": st.session_state.initial_context['topic']}
                    st.session_state.initial_context.update(revised_state)
                    st.session_state.chapters = revised_state.get("chapters_to_write", [])
                    st.session_state.syllabus_ready = True
                    st.rerun()
                except Exception as e:
                    st.error(f"Failed to revise syllabus: {e}")

with c3:
    if st.button("❌ Cancel Process"):
        st.session_state.syllabus_ready = False
        st.session_state.chapters = []
        st.session_state.initial_context = {}
        st.rerun()